<a href="https://colab.research.google.com/github/gc2321/3235-Machine-Learning/blob/main/XTRA_NEURO_NET_EXERCISES/4_nlp_shakespeare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import random
import tensorflow as tf
random.seed(42)

In [2]:
# Mount Google drive
from google.colab import drive
drive.mount('/content/gdrive')

import fileinput
filePath ="/content/gdrive/MyDrive/neural_data/shakespeare.txt"


Mounted at /content/gdrive


In [3]:
text = open(filePath, 'r').read()

In [4]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [5]:
tf.__version__

'2.15.0'

In [6]:
# The unique characters in the file
vocab = sorted(set(text))
print(vocab)
len(vocab)

['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '}']


84

## Text Processing

In [7]:
char_to_ind = {u:i for i, u in enumerate(vocab)}

In [8]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [9]:
ind_to_char = np.array(vocab)

In [10]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [11]:
# encode the full text as np array
encoded_text = np.array([char_to_ind[c] for c in text])

In [12]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [13]:
sample = text[:20]
sample

'\n                   '

In [14]:
encoded_text[:20]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Creating Batches

In [15]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [16]:
# choose seq_len = 120, captures enough information
seq_len = 120

In [17]:
total_num_seq = len(text)//(seq_len+1)

In [18]:
total_num_seq

45005

In [19]:
# Create Training Sequences
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

#for i in char_dataset.take(500):
     #print(ind_to_char[i.numpy()])

In [20]:
# drop last few char
sequences = char_dataset.batch(seq_len+1, drop_remainder=True)

In [21]:
sequences

<_BatchDataset element_spec=TensorSpec(shape=(121,), dtype=tf.int64, name=None)>

In [22]:
def create_seq_targets(seq):
    input_txt = seq[:-1] # 119 in size, take everything except last char
    target_txt = seq[1:] # 119 in size, starting index 1 to last char
    return input_txt, target_txt


In [23]:
dataset = sequences.map(create_seq_targets)

In [24]:
for input_txt, target_txt in  dataset.take(1):
    print(input_txt.numpy())
    print(''.join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    # There is an extra whitespace!
    print(''.join(ind_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


## Generating Training Batches

In [25]:
# Batch size
batch_size = 128

# Buffer size to shuffle the dataset so it doesn't attempt to shuffle
# the entire sequence in memory. Instead, it maintains a buffer in which it shuffles elements
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size, drop_remainder=True)

In [26]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

In [27]:
# training: input sequence, (128, 120), output sequence (128, 120)
128 * 120

15360

## Creating the Model

In [28]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embed_dim = 64 # choose number around size of vocab_size

# Number of RNN units
rnn_neurons = 1026

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

In [30]:
# set up loss function
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [31]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2

In [32]:
def sparse_cat_loss(y_true,y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [33]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
    model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    # Final Dense Layer to Predict
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [34]:
model = create_model(
  vocab_size = vocab_size,
  embed_dim=embed_dim,
  rnn_neurons=rnn_neurons,
  batch_size=batch_size)

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## Training the Model

In [36]:
for input_example_batch, target_example_batch in dataset.take(1):

  # Predict off some random batch
  example_batch_predictions = model(input_example_batch)

  # Display the dimensions of the predictions
  print(example_batch_predictions.shape, " <=== (batch_size, sequence_length, vocab_size)")


(128, 120, 84)  <=== (batch_size, sequence_length, vocab_size)


In [37]:
example_batch_predictions[:2]

<tf.Tensor: shape=(2, 120, 84), dtype=float32, numpy=
array([[[-2.5193277e-03, -1.8753652e-03,  5.9945877e-03, ...,
          1.6431784e-03,  7.1835809e-04, -3.4081351e-03],
        [-3.8625891e-04,  4.8523936e-03,  1.1120542e-03, ...,
          4.9501029e-03,  5.0171721e-04,  1.3376519e-04],
        [-3.1771436e-03,  3.7739999e-04,  7.4787457e-03, ...,
          3.7570845e-03,  1.7160567e-04, -2.7378884e-03],
        ...,
        [ 7.5884988e-03, -1.4314558e-03,  3.5555828e-03, ...,
          2.8131339e-03,  3.5148561e-03,  2.0127418e-03],
        [ 1.0935766e-02, -1.9866542e-03, -3.4138424e-04, ...,
         -1.3025652e-03, -1.6758287e-03,  6.1892453e-03],
        [-4.6486361e-03,  5.4714303e-03, -2.9197647e-03, ...,
         -2.2591809e-03, -4.9038543e-03, -7.5034040e-04]],

       [[-5.0809546e-03,  2.3677556e-03, -3.9995727e-03, ...,
         -4.7638225e-03,  7.7128420e-03,  1.4557011e-04],
        [-8.1059188e-03,  2.2687304e-03, -5.5921185e-03, ...,
         -6.8859905e-03,  1.0

In [38]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [39]:
sampled_indices[:5]

<tf.Tensor: shape=(5, 1), dtype=int64, numpy=
array([[64],
       [ 2],
       [69],
       [37],
       [20]])>

In [40]:
# Reformat to not be a lists of lists
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [41]:
sampled_indices[:2]

array([64,  2])

In [42]:
print("Given the input seq: \n")
print("".join(ind_to_char[input_example_batch[0]]))
print('\n')
print("Next Char Predictions: \n")
print("".join(ind_to_char[sampled_indices ]))

Given the input seq: 

ses them. IRAS falls and dies]
    Have I the aspic in my lips? Dost fall?
    If thus thou and nature can so gently par


Next Char Predictions: 

i!nL9]D_e5-4i6o4Sre}N_;hqk:n'|ue`[
EIh1DbCa2HzsWCKQkyZqrPtS;m7u]RBhY}tV4K?&pGoq`)6XT69X7p]xzh.7FETt&C5pzGK5qxPD?,AFckXgS


In [43]:
# now training model
epochs = 30
model.fit(dataset,epochs=epochs)

Epoch 1/30
351/351 [==============================] - 53s 138ms/step - loss: 2.5592
Epoch 2/30
351/351 [==============================] - 54s 148ms/step - loss: 1.7599
Epoch 3/30
351/351 [==============================] - 52s 143ms/step - loss: 1.4835
Epoch 4/30
351/351 [==============================] - 53s 147ms/step - loss: 1.3553
Epoch 5/30
351/351 [==============================] - 55s 150ms/step - loss: 1.2882
Epoch 6/30
351/351 [==============================] - 54s 149ms/step - loss: 1.2456
Epoch 7/30
351/351 [==============================] - 54s 149ms/step - loss: 1.2141
Epoch 8/30
351/351 [==============================] - 53s 144ms/step - loss: 1.1893
Epoch 9/30
351/351 [==============================] - 55s 150ms/step - loss: 1.1684
Epoch 10/30
351/351 [==============================] - 52s 144ms/step - loss: 1.1508
Epoch 11/30
351/351 [==============================] - 53s 146ms/step - loss: 1.1346
Epoch 12/30
351/351 [==============================] - 55s 150ms/step - lo

## Generating Text

In [43]:
# model.save('shakespeare_gen.h5')
# from tensorflow.keras.models import load_model
# model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)

# model.load_weights('shakespeare_gen.h5')

# model.build(tf.TensorShape([1, None]))

In [54]:
def generate_text(model, start_seed,gen_size=100,temp=1.0):
  '''
  model: Trained Model to Generate Text
  start_seed: Intial Seed text in string form
  gen_size: Number of characters to generate

  Basic idea behind this function is to take in some seed text, format it so
  that it is in the correct shape for our network, then loop the sequence as
  we keep adding our own predicted characters. Similar to our work in the RNN
  time series problems.
  '''

  # Number of characters to generate
  num_generate = gen_size

  # Vecotrizing starting seed text
  input_eval = [char_to_ind[s] for s in start_seed]

  # Expand to match batch format shape
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty list to hold resulting generated text
  text_generated = []

  # Temperature effects randomness in our resulting text
  # The term is derived from entropy/thermodynamics.
  # The temperature is used to effect probability of next characters.
  # Higher probability == lesss surprising/ more expected
  # Lower temperature == more surprising / less expected

  temperature = temp

  # Here batch size == 1
  model.reset_states()

  for i in range(num_generate):

      # Generate Predictions
      predictions = model(input_eval)

      # Remove the batch shape dimension
      predictions = tf.squeeze(predictions, 0)

      # Use a cateogircal disitribution to select the next character
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # Pass the predicted charracter for the next input
      input_eval = tf.expand_dims([predicted_id], 0)

      # Transform back to character letter
      text_generated.append(ind_to_char[predicted_id])

  return (start_seed + ''.join(text_generated))

In [45]:
print(generate_text(model,"flower",gen_size=1000))

ValueError: Exception encountered when calling layer 'sequential' (type Sequential).

Input 0 of layer "gru" is incompatible with the layer: expected shape=(128, None, 64), found shape=(1, 6, 64)

Call arguments received by layer 'sequential' (type Sequential):
  • inputs=tf.Tensor(shape=(1, 6), dtype=int32)
  • training=None
  • mask=None