<a href="https://colab.research.google.com/github/gc2321/3235-Machine-Learning/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch

In [20]:
print(torch.__version__)

2.5.0+cu121


In [21]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [22]:
scalar.ndim

0

In [23]:
scalar.item()

7

In [24]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [25]:
vector.ndim

1

In [26]:
vector.shape

torch.Size([2])

In [27]:
print(vector)
for item in vector:
  item

tensor([7, 7])


In [28]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [29]:
MATRIX.ndim

2

In [30]:
MATRIX.shape

torch.Size([2, 2])

In [31]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [32]:
TENSOR.ndim

3

In [33]:
TENSOR.shape

torch.Size([1, 3, 3])