<a href="https://colab.research.google.com/github/gc2321/3235-Machine-Learning/blob/main/XTRA_NLP/5_topic_modeling_nmf_2_questions_and_answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving quora_questions.csv to quora_questions.csv


In [3]:
import numpy as np
import pandas as pd

quora = pd.read_csv('quora_questions.csv')
quora.head()

Question
0  What is the step by step guide to invest in sh...
1  What is the story of Kohinoor (Koh-i-Noor) Dia...
2  How can I increase the speed of my internet co...
3  Why am I mentally very lonely? How can I solve...
4  Which one dissolve in water quikly sugar, salt...

In [6]:
len(quora)

404289

## Preprocessing

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [11]:
dtm = tfidf.fit_transform(quora['Question'])

In [8]:
dtm

<404289x38669 sparse matrix of type '<class 'numpy.float64'>'
	with 2002912 stored elements in Compressed Sparse Row format>

## NMF

In [12]:
from sklearn.decomposition import NMF

In [13]:
nmf_model = NMF(n_components=20,random_state=42)

In [14]:
nmf_model.fit(dtm)

/usr/local/lib/python3.10/dist-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


NMF(n_components=20, random_state=42)

In [15]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['thing', 'read', 'place', 'visit', 'places', 'phone', 'buy', 'laptop', 'movie', 'ways', '2016', 'books', 'book', 'movies', 'best']


THE TOP 15 WORDS FOR TOPIC #1
['majors', 'recruit', 'sex', 'looking', 'differ', 'use', 'exist', 'really', 'compare', 'cost', 'long', 'feel', 'work', 'mean', 'does']


THE TOP 15 WORDS FOR TOPIC #2
['add', 'answered', 'needing', 'post', 'easily', 'improvement', 'delete', 'asked', 'google', 'answers', 'answer', 'ask', 'question', 'questions', 'quora']


THE TOP 15 WORDS FOR TOPIC #3
['using', 'website', 'investment', 'friends', 'black', 'internet', 'free', 'home', 'easy', 'youtube', 'ways', 'earn', 'online', 'make', 'money']


THE TOP 15 WORDS FOR TOPIC #4
['balance', 'earth', 'day', 'death', 'changed', 'live', 'want', 'change', 'moment', 'real', 'important', 'thing', 'meaning', 'purpose', 'life']


THE TOP 15 WORDS FOR TOPIC #5
['reservation', 'engineering', 'minister', 'president', 'company', 'china', 'business', 'country', 

## Discover Topic Labels to Original Articles

In [16]:
dtm.shape

(404289, 38669)

In [17]:
len(quora)

404289

In [18]:
topic_results = nmf_model.transform(dtm)

In [19]:
topic_results.shape

(404289, 20)

In [20]:
topic_results[0]


array([2.74927015e-04, 5.88014577e-05, 6.17412189e-06, 4.95620733e-04,
       3.93020250e-05, 2.61336884e-02, 3.90468377e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 2.33820194e-04, 1.15818171e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.97335523e-04,
       0.00000000e+00, 6.97429434e-04, 2.13458466e-04, 0.00000000e+00])

In [21]:
topic_results[0].round(2)

array([0.  , 0.  , 0.  , 0.  , 0.  , 0.03, 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [22]:
topic_results[0].argmax()

5

## Combine with Original Data

In [23]:
topic_results.argmax(axis=1)

array([ 5, 16, 17, ..., 11, 11,  9])

In [24]:
quora['Topic'] = topic_results.argmax(axis=1)

In [25]:
quora.head(10)

Question  Topic
0  What is the step by step guide to invest in sh...      5
1  What is the story of Kohinoor (Koh-i-Noor) Dia...     16
2  How can I increase the speed of my internet co...     17
3  Why am I mentally very lonely? How can I solve...     11
4  Which one dissolve in water quikly sugar, salt...     14
5  Astrology: I am a Capricorn Sun Cap moon and c...      1
6                                Should I buy tiago?      0
7                     How can I be a good geologist?     10
8                    When do you use シ instead of し?     19
9  Motorola (company): Can I hack my Charter Moto...     17